# Introduction to MATLAB
MATLAB, which stands for Matrix Laboratory, is an integrated technical computing environment.

It is used for:
- Mathematics and computation.
- Algorithm development and data analysis.
- Graphing functions and solving equations.
- Modelling and simulation.

**Note**: for these interactive notes, we are using _**GNU Octave**_, which is an open source alternative to _**Matlab**_ (it is licensed)

## MATLAB Windows
MATLAB has four main windows:

- Command Window: The main area where you type commands and instructions to interact with MATLAB.
- Command History: Contains a history of the commands you have entered, which helps in repeating, copying, or modifying previous commands.
- Workspace Browser: Shows all the variables you have created during a session.
- Current Directory Browser: Shows the files and folders in your current working directory, which is where new files are stored.

## Input and Output
- Input: You provide input by typing commands directly into the command window and pressing Enter.
- Output: MATLAB returns output in two ways:
  - Text or numerical output is shown in the command window.
  - Graphical output appears in a separate graphics window.

## Getting Help

- MATLAB Help Browser: You can open the built-in help browser by clicking the Help icon (question mark) on the Home tab or by typing `doc` in the command window.
- Command Line Help: You can get quick help from the command window.
  - `help function-name`: Provides a brief explanation of a function. For example, `help plot`. This command can run directly from inside the interacitve notes;
  - `doc function-name`: Opens the detailed documentation for a function in the Help Browser. For example, `doc plot`. This command has to be run from Matlab itself and it will open a new window, which is why it can't be run here. You can try, but you will need to restart the kernel after.

In [1]:
disp('help command');
help plot;











The FLTK graphics toolkit is not actively maintained and has a number
of limitations that are unlikely to be fixed.
The qt toolkit is recommended instead.







help command

'plot' is a function from the file /usr/share/octave/9.4.0/m/plot/draw/plot.m

 -- plot (Y)
 -- plot (X, Y)
 -- plot (X, Y, FMT)
 -- plot (..., PROPERTY, VALUE, ...)
 -- plot (X1, Y1, ..., XN, YN)
 -- plot (HAX, ...)
 -- H = plot (...)
     Produce 2-D plots.

     Many different combinations of arguments are possible.  The
     simplest form is

          plot (Y)

     where the argument is taken as the set of Y coordinates and the X
     coordinates are taken to be the range ‘1:numel (Y)’.

     If more than one argument is given, they are interpreted as

          plot (Y, PROPERTY, VALUE, ...)

     or

          plot (X, Y, PROPERTY, VALUE, ...)

     or

          plot (X, Y, FMT, ...)

     and so on.  Any number of argument sets may appear.  The X and Y
     values are interpreted as follows:



# Basic Operations and Concepts

## Arithmetic Operations

You can perform standard arithmetic operations directly in the command window.

- Addition: `10 + 5`

In [2]:
10 + 5


ans = 15


- Subtraction: `10 - 5`

In [3]:
10 - 5


ans = 5


- Multiplication: `10 * 5`

In [4]:
10 * 5


ans = 50


- Division: `10 / 5`

In [5]:
10 / 5


ans = 2


- Exponentiation: `4^2`

In [6]:
4 ^ 2


ans = 16


- Square Root: `sqrt(ans)`

In [7]:
sqrt(4^2)


ans = 4


## Using Variables

When you perform an operation without assigning it to a variable, the result is stored in a temporary variable called `ans` (If you have wondered why above there is an `ans = ` output in all cells). Only the result of the very last operation is saved. To avoid this and save results, you should assign them to variables.

```matlab
a = 10;
b = 5;
c = a + b
d = a - b
e = a * b
f = a / b
```

To prevent a command's output from being displayed in the command window, add a semicolon (;) to the end of the line.

In [8]:
a = 10;
b = 5;
c = a + b
d = a - b
e = a * b
f = a / b




c = 15

d = 5

e = 50

f = 2


Note that the values of all variables other than `a` and `b` were printed out, because we did not add the semicolon (;) at the end. You can modify the lines above and rerun the cell to check what happens.

## Floating Point Display

MATLAB's default display for numbers is 5 digits (short format). You can change this using the `format` command.

- `format long`: Displays 15 digits.
- `format short`: Resets to the default 5-digit display.
- `format rat`: Displays numbers as rational fractions.


In [9]:
# Long Format
format long;
disp(sqrt(2));




1.414213562373095


In [10]:
# Short (default) format
format short;
disp(sqrt(2));




1.4142


In [11]:
# Rational fractions format
format rat;
disp(sqrt(2));
# Remember that sqrt(2) is not a rational number so this is only an approximation




8119/5741



In [12]:
# Reset the format to the default
format short;

## Scientific Notation

You can express numbers using scientific notation with the letter 'e'.

- `4.5 * 10^9` is written as `4.5e9`.
- `3.123 * 10^-7` is written as `3.123e-7`.

In [13]:
disp(4.5 * 10^9)
disp(4.5e9)


4.5000e+09

4.5000e+09


In [14]:
disp(3.123 * 10^-7)
disp(3.123e-7)


3.1230e-07

3.1230e-07


# Working with Matrices and Vectors

## Creating Matrices and Vectors

Matrices are the core of MATLAB. To create a matrix, you enclose the elements in square brackets. You can use spaces or commas (,) to separate elements in a row, and semicolons (;) or the Enter key to start a new row.

```matlab
A = [a b c; d e f]
```

Vectors are matrices with only one row or one column.

- Row vector: `A = [1 2 3 4]`
- Column vector: `A = [1; 2; 3; 4]`

To create a vector of sequential numbers, you can use the colon (:) operator `start:step:end`.

- `C = 1:2:9` creates `[1 3 5 7 9]`.
- `C = 1:6` creates `[1 2 3 4 5 6]` (default step is 1).
- `C = 6:-1:1` creates `[6 5 4 3 2 1]`.

In [15]:
row_vector = [1 2 3 4]
column_vector = [1; 2; 3; 4]
odds = 1:2:9
vector1_6 = 1:6
vector6_1 = 6:-1:1


row_vector =

   1   2   3   4


column_vector =

   1
   2
   3
   4


odds =

   1   3   5   7   9


vector1_6 =

   1   2   3   4   5   6


vector6_1 =

   6   5   4   3   2   1



## Basic Matrix Operations

- Addition and Subtraction: Performed element by element. The matrices must have the same dimensions. `C = A + B`.

In [16]:
A = [1:3; 4:6];
B = [2:4; 5:7];
C = A + B
D = B - A




C =

    3    5    7
    9   11   13


D =

   1   1   1
   1   1   1



In [17]:
a = 1:3
# This will run normally since it will just extend it
B - a


a =

   1   2   3



ans =

   1   1   1
   4   4   4



In [18]:
a = 1:4
# This will be an error
B - a


a =

   1   2   3   4



error: operator -: nonconformant arguments (op1 is 2x3, op2 is 1x4)


- Multiplication: For standard matrix multiplication (`C = A * B`), the number of columns in matrix A must equal the number of rows in matrix B.

In [19]:
v = [1; 2; 3];
A * v



ans =

   14
   32



- Inverse: The `inv()` function is used to find the inverse of a square matrix. `inv(A)`.

In [20]:
inv([1:2; 3:4])


ans =

  -2.0000   1.0000
   1.5000  -0.5000



In [21]:
inv(A)


error: inv: A must be a square matrix


- Power: You can raise a square matrix to a power using the `^` operator, which is equivalent to multiplying the matrix by itself that number of times. `B = A^2` is the same as `B = A*A`.

In [22]:
S = [1:3; 4:6; 7:9];
S^2



ans =

    30    36    42
    66    81    96
   102   126   150



In [23]:
A^2


error: for x^y, only square matrix arguments are permitted and one argument must be scalar.  Use .^ for elementwise power.


- Transpose: The transpose of a matrix swaps its rows and columns. It is done using a single quote (`'`).

In [24]:
A'
B'
C'
S'
v'


ans =

   1   4
   2   5
   3   6


ans =

   2   5
   3   6
   4   7


ans =

    3    9
    5   11
    7   13


ans =

   1   4   7
   2   5   8
   3   6   9


ans =

   1   2   3



## Element-wise Operations

To perform operations like multiplication, division, or exponentiation on an element-by-element basis (instead of using standard matrix rules), you must place a dot (**.**) before the operator.

- `B = A.*A`
- `C = A.^3`

In [25]:
A.*A # Multiply each element by itself
A.*2 # Multiply each element by 2
A.^2 # Raise all elements to the power 2
A.^3 # Raise all elements to the power 3


ans =

    1    4    9
   16   25   36


ans =

    2    4    6
    8   10   12


ans =

    1    4    9
   16   25   36


ans =

     1     8    27
    64   125   216



## Matrix and Vector Properties

- `size(A)`: Returns the dimensions of the matrix (number of rows and columns).
  - `size(A,1)`: Returns only the number of rows.
  - `size(A,2)`: Returns only the number of columns.
- `length(A)`: Returns the length of a vector.
- `max(A)`: If A is a matrix, returns a row vector with the maximum value from each column. `max(max(A))` finds the single largest element in the matrix.
- `min(A)`: Works the same way as `max` but finds minimum values.
- `sum(A)`: If A is a matrix, returns a row vector with the sum of each column. `sum(sum(A))` finds the sum of all elements.
- `prod(A)`: Works the same way as `sum` but finds the product of the elements.

In [26]:
A
size(A)
size(A, 1)
size(A, 2)
length(A)
max(A)
max(max(A))
min(A)
min(min(A))
sum(A)
sum(sum(A))
prod(A)
prod(prod(A))


A =

   1   2   3
   4   5   6


ans =

   2   3


ans = 2

ans = 3

ans = 3

ans =

   4   5   6


ans = 6

ans =

   1   2   3


ans = 1

ans =

   5   7   9


ans = 21

ans =

    4   10   18


ans = 720


## Accessing and Modifying Elements

You can access an element by its row and column index: `A(row, col)`.

- `A(2,3) = 10`: Assigns the value 10 to the element in the second row, third column.
- `A(3, 1:2) = [1 5]`: Assigns the values 1 and 5 to the first two columns of the third row.
- To delete an element from a vector, assign an empty bracket to it: `A(10) = []`.

In [27]:
A(2, 3) = 20
A(1, 2:3) = [3 5]
A(1:2, 3) = [7 9]
A(2, 3) = []


A =

    1    2    3
    4    5   20


A =

    1    3    5
    4    5   20


A =

   1   3   7
   4   5   9


error: a null assignment can only have one non-colon index


In [28]:
v
v(3) = []


v =

   1
   2
   3


v =

   1
   2



## Special Matrices

- `diag(A)`: Extracts the main diagonal of matrix A.
- `triu(A)`: Creates the upper triangular part of matrix A.
- `tril(A)`: Creates the lower triangular part of matrix A.
- `zeros(m,n)`: Creates an m-by-n matrix of zeros.
- `ones(m,n)`: Creates an m-by-n matrix of ones.
- `eye(n)`: Creates an n-by-n identity matrix, with ones on the main diagonal and zeros elsewhere.

In [29]:
diag(A)
triu(A)
tril(A)
zeros(3,2)
ones(2,3)
eye(3)


ans =

   1
   5


ans =

   1   3   7
   0   5   9


ans =

   1   0   0
   4   5   0


ans =

   0   0
   0   0
   0   0


ans =

   1   1   1
   1   1   1


ans =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1



# MATLAB Programming (M-Files)

M-files are files that contain MATLAB statements. There are two kinds of M-files: script files and function files.

## Script M-Files

Scripts are a simple sequence of MATLAB commands. When you run the script (by typing its name in the command window), it is as if you typed each command sequentially.

## Function M-Files

Functions are more flexible and can accept input arguments and return output values.

- A function file must begin with a function definition line, which specifies the function's name, inputs, and outputs.
- The file should be saved with the same name as the function name (e.g., a function named `add_sub` should be saved in a file named `add_sub.m`).

Example of a function file:

```matlab
function [x, y] = add_sub(a, b)
x = a + b;
y = a - b;
end
```

In [30]:
function [x, y] = add_sub(a, b)
x = a + b;
y = a - b;
end

In [31]:
[x, y] = add_sub(1, 0)


x = 1
y = 1


## Control Flow: Loops

Loops repeat a group of commands multiple times.

- `for` loop: Repeats for a specified number of times.
  ```matlab
  f = 1;
  for n = 2:10
      f = f * n;
  end
  ```
- `while` loop: Repeats as long as a condition is true. Be careful, as this can lead to an infinite loop if the condition is never met. You can usually stop execution with CTRL+C.


In [32]:
# This is a way to calculate the factorial of 6
f = 1; # The variable that will save the value
for n = 2:6
    f = f * n;
end
disp(f)







720
